### ISSUE TITLE
Doesn't work with Angular 15

### ISSUE THREAD

**Issue by HarryPitsillides** [microsoft/powerbi-client-angular#43]
Attempting to use this with Angular 15, since as per the documentation this works with >=13, but keep getting  'powerbi-report' is not a known element, this is true for all Power Bi components.

To state the obvious I have imported the PowerBiEmbedModule in my standalone component and in my importProvidersFrom when routing to ensure all services have been loaded.

**Comment by MMWWMMWWMM** [comment]
I get the same error
angular 13
the examples do not work
is it bound to a specific version?

**Comment by v-MadhavC** [comment]
Hello, we have tried to reproduce the issue you mentioned.

 

We created a sample Angular 15 application and imported PowerBIEmbedModule in order to embed the report.

 

We are not facing any errors following above steps. Are there any specific steps that we need to follow.

 

Could you please provide steps to reproduce the error?

**Comment by may-hartov** [comment]
Required details for troubleshooting were not provided, closing the issue.

**Comment by chaukhaphan** [comment]
It doesnt work for me as well.
