### ISSUE TITLE
Angular 16 Support

### ISSUE THREAD

**Issue by onetimefortheonetime** [microsoft/powerbi-client-angular#49]
Is there a release planned to support Ivy Compilation, which is required for Angular 16?

**Comment by v-MadhavC** [comment]
Hello, we have tried to reproduce the issue, but we are able to successfully embed Power BI report using Angular 16.

In order to help you better can you please share some more information regarding what error are you are facing and maybe some code snapshot of how you are embedding the report and some steps to reproduce the issue.

**Comment by onetimefortheonetime** [comment]
Hi @v-MadhavC. I get this error when attempting to build

![image](https://github.com/microsoft/powerbi-client-angular/assets/147530758/ba59f147-1b66-4525-abb8-c428c0bc013e)

**Comment by v-MadhavC** [comment]
Hello, We tried to reproduce the issue. We created a new Angular 16 Application and enabled IVY in the `tsconfig.app.json`. 

We executed 'ng-build' and embedded sample Power BI report.
We are not facing any errors following above steps. Are there specific any steps that we need to follow. 

Could you please provide steps to reproduce the error?

**Comment by onetimefortheonetime** [comment]
Thanks for trying to reproduce my issue @v-MadhavC. We are using module federation to serve about a dozen or so microfrontends. I will try again and post here if I still run into the issue after rechecking the versions and tsconfigs.

**Comment by onetimefortheonetime** [comment]
I resolved this by running
ng generate @angular/core:standalone
