### ISSUE TITLE
Can someone please explain how the token is delivered?

### ISSUE THREAD

**Issue by RupenAnjaria** [microsoft/powerbi-client-angular#50]
As per the code we are calling an API: https://aka.ms/CaptureViewsReportEmbedConfig
This API returns token and other details. I don't understand what the API URL is doing? is it just returning some hardcoded data? If I have a PowerBI report then how can I generate these details?

Thank you.

**Comment by v-MadhavC** [comment]
Hello, in order to embed a Power BI report using powerbi-client-angular we have to pass reportID, embedURL and embedToken. In order to generate embedURL and embedToken for you Power BI report please follow the following documentations:

 

**Embed URL:**
In order to generate embed URL we need to pass groupID.
https://learn.microsoft.com/en-us/rest/api/power-bi/reports/get-reports-in-group#code-try-0

**Embed Token:**
In order to generate embed Token we need to pass groupID and reportID along with the requestBody.
 
![image](https://github.com/microsoft/powerbi-client-angular/assets/126773262/df2569a1-ccdd-45f5-8706-d7e6e05ec722)

https://learn.microsoft.com/en-us/rest/api/power-bi/embed-token/reports-generate-token-in-group#code-try-0

 

Hope this helps, if you still have some queries, please feel free to reach out to us.

**Comment by RupenAnjaria** [comment]
Thank you for the quick response. This was really helpful as I was able to integrate my report. 

Questions:

1. Is there any authentication for those APIs? or just passing GroupId and Reportid is enough.
2. Will GroupId stay same for all my PowerBI reports within my company? I believe so.
3. May I please see what is the code for https://aka.ms/CaptureViewsReportEmbedConfig? I mean, what is it doing behind the scene? Is it calling two APIs and combining the results?

Thanks again.

**Comment by RupenAnjaria** [comment]
That was helpful and I am seems making progress, however regarding the URL you shared (https://learn.microsoft.com/en-us/rest/api/power-bi/reports/get-reports-in-group#code-try-0) I am just curious about from where does it gets the token in the playground section:

See the image below:
![image](https://github.com/microsoft/powerbi-client-angular/assets/17281745/8e836903-83fd-49cf-a63c-ecabb76d48c4)

This is the only last piece where I am stuck.

**Comment by KotanaSai21** [comment]
The Error you're facing while getting the Embed URL PowerBINotAuthorizedException is due to either Unauthorized group or wrong group Id. Refer [Troubleshoot documentation](https://learn.microsoft.com/en-us/power-bi/developer/embedded/embedded-troubleshoot#typical-errors-when-embedding-for-power-bi-users:%7E:text=match%20token%20type-,PowerBINotAuthorizedException,Unauthorized%20group,-TokenExpired) for the Error details.

Refer to this documentation [Embed using service principal](https://learn.microsoft.com/en-us/power-bi/developer/embedded/embed-service-principal). Follow the steps, where you need to add service principal to your workspace. Then You would be able to hit the API and get the Embed URL.

Feel free to reach out if you have any other queries.

**Comment by RupenAnjaria** [comment]
Sure, but I am able to integrate the report even without these settings. 
Here is what I did:

1. Visit [sample](https://learn.microsoft.com/en-us/rest/api/power-bi/reports/get-reports-in-group#code-try-0)
2. Copy the Bearer token
3. Make a call to https://api.powerbi.com/v1.0/myorg/groups/{groupid}/reports/{reportid} using the token
4. Copy the EmbedURL from the response
5. Use above values (token and URL) in your Angular demo app (in app.component.ts:
```
    // Update the reportConfig to embed the PowerBI report
    this.reportConfig = {
      ...this.reportConfig,
      id: '{reportID}', //reportConfigResponse.Id,
      embedUrl: '{embedURL}',  //reportConfigResponse.EmbedUrl,
      accessToken:  '{token}', //reportConfigResponse.EmbedToken.Token,
    };
```


if I take a token from  it is working fine. So not sure if we have to make additional changes in the Entra. Please suggest.

**Comment by RupenAnjaria** [comment]
@KotanaSai21 Please close this as I was able to integrate after allowing the Entra app in powerbi workspace.

**Comment by RupenAnjaria** [comment]
@KotanaSai21 Please close this as I was able to integrate after allowing the Entra app in powerbi workspace.

**Comment by jaspreet1234567** [comment]
@RupenAnjaria - From where you getting the bearer token? I am bit confused here. Here is my understanding, Please correct me if I'm wrong:

- First get the bearer token from azure active directory.
- Then by using this token, get the embed url and embed token.
- Pass this embed token and url in config to embed the report.

Thanks in advance.
