### ISSUE TITLE
ERROR Error: Invalid embed URL detected. Either URL hostname or protocol are invalid. Please use Power BI REST APIs to get the valid URL

### ISSUE THREAD

**Issue by jitinpurwal** [microsoft/powerbi-client-angular#60]
![image](https://github.com/microsoft/powerbi-client-angular/assets/21660536/4c920224-0a05-4991-89f7-d2793f5d4fab)

on second click ee.validateEmbedUrl return true and on first click it return false. this is inconsistent. please fix it

I am using powerbi-report-angular version 3.0.5

**Comment by KotanaSai21** [comment]
This issue is with the powerbi-client package and it has been fixed in the latest [version](https://www.npmjs.com/package/powerbi-client/v/2.23.1https://www.npmjs.com/package/powerbi-client/v/2.23.1). Please override the version in package.json to  `powerbi-client: 2.23.1`.

We're currently working on the Angular package and will try to release version soon with updating the package versions.

**Comment by jitinpurwal** [comment]
Hi, but i am using powerbi-client-angular 3.0.5. 
can i use powerbi-client: 2.23.1 instead of powerbi-client-angular 3.0.5. in my angular project?

**Comment by KotanaSai21** [comment]
We need to override the version of `powerbi-client` package coming from the `powerbi-client-angular`. Check the below code to be included in package.json

```
 "powerbi-client-angular": "^3.0.5",
 "powerbi-client": "^2.23.1"
```

This should override the powerbi-client version and you should able to embed the report. Let me know if you still have any queries.
